### PR TITLE
Attach Build Log to Email

### PR DESCRIPTION
**Pull request by maronesy**
This feature gives the user the option to attach build log to the regression email via a checkbox in the configuration.

### CODE REVIEW

**Comment by KengoTODA** [comment]
Thanks for your contribution, your patch looks really great.
I want to release version 1.5 after the merge, so could you please:

- [ ] Update `screenshot.png` which is used by wiki and `README.md`. Feel free to change its size if you need.
- [ ] Add changelog about version 1.5 in `README.md`.

Thanks in advance!

**Comment by maronesy** [comment]
It was our pleasure! Thank you for accepting our request!
The changes you requested are complete.  Please let us know if there is anything else you want us to change.

Thanks Again!

**Comment by KengoTODA** [comment]
I've merged this PR. Thanks!

I will release version 1.5 later.

**Comment by KengoTODA** [comment]
version 1.5 is successfully published, please try to use.

**Comment by fchandra09** [comment]
I have tested version 1.5 and confirmed that attaching build log is working correctly. Thanks!

**Pull request merged**
